require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - vendor/**/*
    - db/**/*
    - db/schema.rb
    - node_modules/**/*
    - bin/*

Metrics/BlockLength:
  Exclude:
    - lib/tasks/**/*
    - spec/**/*

Metrics/LineLength:
  IgnoredPatterns: [(\A|\s)#]
  Exclude:
    - db/**/*
    - spec/rails_helper.rb

Rails/UnknownEnv:
  Environments:
    - production
    - staging
    - review
    - test
    - development

Style/Documentation:
  Exclude:
    - app/**/application_*.rb
    - config/application.rb
